---
- name: Flint Installation
  hosts: localhost
  become: yes
  vars:
    nodejs_version: 21
    flint_path: "/root/Flint"

  tasks:
    - name: Adding Yum Repository
      ansible.builtin.yum:
        name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm"
        state: present
        validate_certs: no

    - name: Installation
      block:
        - name: installing nodejs, mysql, python3, pip
          ansible.builtin.package:
            name:
              - python3
              - python3-pip
              - mysql-server
            state: latest

        - name: installing openai
          ansible.builtin.shell: pip3 install openai
            
        - name: installing express module
          community.general.npm:
            name: express
            path: "{{ flint_path }}"

        - name: installing embedded javascript
          community.general.npm:
            name: ejs
            path: "{{ flint_path }}"

        - name: installing mysql module
          community.general.npm:
            name: mysql
            path: "{{ flint_path }}"

        - name: installing express js and dashboard
          ansible.builtin.shell: |
            cd "{{ flint_path }}"
            wget https://raw.githubusercontent.com/stup109/Flint/main/index.js
            mkdir views
            wget https://raw.githubusercontent.com/stup109/Flint/main/index.ejs
            mv index.ejs views/
        
        - name: installing create-react-app
          ansible.builtin.shell: |            
            npm install create-react-app
            create-react-app "{{ flint_path }}/web"
            cd "{{ flint_path }}/web/src"
            shopt -s extglob
            rm -v !("index.css")
            wget https://raw.githubusercontent.com/stup109/Flint/main/App/web/src/index.js
            
    - name: Generating Restful Api
      block:
      - name: Restful Folder Create
        ansible.builtin.file:
          path: "{{ flint_path }}/restful"
          state: directory
          mode: '0755'
...
