---
- name: Flint Installation
  hosts: localhost
  become: yes
  vars:
    nodejs_version: 21
    flint_path: "/root/Flint"

  tasks:
    - name: Add NodeJS Yum Repository
      ansible.builtin.yum:
        name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm"
        state: present

    - name: Install Node Packages
      block:
        - name: Install NodeJS
          ansible.builtin.package:
            name:
              - nodejs
              - mysql-server
            state: latest
            
        - name: installing express as backend 
          community.general.npm:
            name: express
            path: "{{ flint_path }}"

        - name: installing package for the connection to mysql
          community.general.npm:
            name: mysql
            path: "{{ flint_path }}"

        - name: installing create-react-app as frontend
          ansible.builtin.shell: |
            cd "{{ flint_path }}"
            npm install create-react-app
            create-react-app "{{ flint_path }}/web"
            cd "{{ flint_path }}/web/src"
            shopt -s extglob
            rm -v !("index.css")
            
    - name: Restful Folder Create
      ansible.builtin.file:
        path: "{{ flint_path }}/restful"
        state: directory
        mode: '0755'
...
