---
- name: Flint Installation
  hosts: localhost
  become: yes
  vars:
    nodejs_version: 21
    flint_path: "/root/Flint"

  tasks:
    - name: Installing Git
      ansible.builtin.yum:
        name: git
        state: present

    - name: Adding Yum Repository
      ansible.builtin.yum:
        name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm"
        state: present
        validate_certs: no

    - name: Create App Folder
      ansible.builtin.shell: |
        git clone https://github.com/stup109/Flint.git flint_cp
        mkdir "{{ flint_path }}"
        mkdir "{{ flint_path }}"/server
        mkdir "{{ flint_path }}"/client

    - name: Installation
      block:
        - name: installing mysql, python3, pip
          ansible.builtin.package:
            name:
              - python3
              - python3-pip
              - mysql
              - mysql-server
            state: latest

        - name: installing gcc python3 openai flask
          ansible.builtin.shell: |
            yum  install gcc python3-devel mysql-devel pkgconfig mysqlclient -y
            pip3 install -U openai Flask flask-cors flask-mysqldb
            
        - name: installing mysql module
          community.general.npm:
            name: mysql
            path: "{{ flint_path }}"
            
        - name: installing and start react
          ansible.builtin.shell: |
            cd "{{ flint_path }}"
            cd "{{ flint_path }}"/client
            npx create-react-app web
            cd web
            npm install react-router-dom react-dom

        - name: adding pages
          ansible.builtin.shell: |
            cd "{{ flint_path }}"
            cd ..
            cp -rf flint_cp/App/web/src/* "{{ flint_path }}"/client/web/src/
            cp flint_cp/App/pyAPI.py "{{ flint_path }}"/server/pyAPI.py
            cp flint_cp/App/index.html "{{ flint_path }}"/server/index.html
            cp flint_cp/App/index.js "{{ flint_path }}"/server/index.js
            cp flint_cp/App/index.py "{{ flint_path }}"/server/index.py
            rm -rf flint_cp
            
        - name: mysql setup
          ansible.builtin.shell: |
            systemctl daemon-reload
            firewall-cmd --zone=public --add-port=3306/tcp --permanent
            firewall-cmd --reload
            systemctl start mysqld.service
            grep -oP "A temporary password is generated for \K\S+: \K\S+" /var/log/mysqld.log >> tpwd.tmp

        - name: installation complete
          ansible.builtin.shell: |
            firefox http://localhost:8080
            
...
